### ISSUE TITLE
One Sync

### ISSUE THREAD

**Issue by plutonmania** [weavyser/esx_civiere#1]
Hello , i love your script. My script is broke , because i m on One sync with 64 slots. Can you Optimise that ? i have test but is wrong for me. THX if you see me.

**Comment by TGMasaryk** [comment]
**Have you modified the following line?**

# for i = 0, 31 do
        if NetworkIsPlayerActive(i) then
            table.insert(players, i)
        end
    end

**Comment by plutonmania** [comment]
yeah it's good , i y a change that with 256. ( im on 64 slot) .
